---
functional:
  -регистрация пользовтелей
  -авиторизация пользователя
  -просмотр личной статистики  
  -возможность создания игры с другими пользователями
  -возможность создания игры с ботом
  -выбор уровня сложности игры
  -выбор задачи для игры
  -просмотр общей статистики игроков
  -возможность писать сообдения в чате игры
  -возможность писать сообщения в общем чате
  -создавать турниры
  -Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  -возможность просматривать профили других игроков
  -возможность создавать свои задачи
  -возможность просматривать историю игры
non-functional:
  -Сайт безопасен и зазщищает данные пользователей
  -Реализована мобильная версия
  -Сайт адаптирован к различным устройствам
  -Сайт обрабатывет большое количество пользователей одновременно
  -Совместимость с последними версиями браузеров
  -Есть вермия для людей с ОВЗ
  -  
implicit:
  -один игрок не может редактировать код соперника
  -время и дата турниры должны быть местными для пользователя
  -
  -
