---
functional:
  -
  


  -регистрация польщовтелей
  -авиторизация пользователя
  -просмотр личной статистики  
  -возможность создания игры с другими пользователями
  -возможность создания игры с ботом
  -выбор уровня сложности игры
  -выбор задачи для игры,
  -просмотр общей статистики игроков
  -возможность писать сообдения в чате игры
  -возмлжность писать сообдения в общем чате
  -создавать турниры

non-functional:
  -
  -
  -
  -
implicit:
  -один игрок не может редактировать код соперника
  -
  -
  -